# Generated by Django 2.1.2 on 2018-11-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='Username',
        ),
    ]
