# Generated by Django 2.1.2 on 2018-11-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181101_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
