# Generated by Django 2.1.2 on 2018-11-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='Photo',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
