# Generated by Django 2.1.2 on 2018-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20181101_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='Photo',
            field=models.ImageField(upload_to='MEDIA_ROOT/'),
        ),
    ]
