# Generated by Django 2.1.2 on 2018-11-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20181101_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='FamilyHead',
            field=models.CharField(default='Jose', max_length=30),
            preserve_default=False,
        ),
    ]
