# Generated by Django 2.1.2 on 2018-11-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_family_familyhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='familyphotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='MEDIA_ROOT/')),
            ],
        ),
    ]
