# Generated by Django 2.1.2 on 2018-11-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_familyphotos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familyphotos',
            new_name='Addfamilyphotos',
        ),
    ]
