# Generated by Django 2.1.2 on 2018-11-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20181102_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='Description',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
